### ISSUE TITLE
Add link to last guide in students view

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#200]
It should go to guide progress.

**Comment by flbulgarelli** [comment]
Hi!

I am reopening this issue - sorry :disappointed: - since with current implementation you are redirecting to the course guide progress, not the user guide progress. This is quite annoying, since you are losing context: 
1. I go to students view. 
2. I discover that Jonny Doe is stuck on lession \* Getting Started*, so I want to see his progress :smile: 
3. I click on the go to last guide link
4. Hmm, I have landed on the course progress... :confused: 
5. I have to search this student again. 
6. Wait.... what was his name? Oh crap, I don't remember. I have to go back to get it :rage:

**Comment by flbulgarelli** [comment]
PS: Is it difficult to add a link in the last submission to the last exercise submitted in the last guide?

Since it is student's last submissions, we can assume it corresponds to the last submitted exercise of the guide. Although we don't have that information on that page, we do have the student and guide, so that path should be easy to calculate, shouldn't it?

**Comment by aguspina** [comment]
But but, the issue specifically says 'guide progress'

**Comment by faloi** [comment]
Sorry, my bad. I was also thinking on student guide progress when I wrote
the issue.

@flbulgarelli, what's the difference between your PS-request and the
current behavior?

**Comment by aguspina** [comment]
Yes it's easy to redirect to student exercise 'guide progress.

**Comment by flbulgarelli** [comment]
@faloi they difference is subtle: in the first case you are redirected to the first exercise of the guide progress of the student. On the latter, you are redirected to the last solved exercise of it.

I am now not so sure it is really important such difference.  Perhaps the  link on the submission date could be he students guide progress, while the guide link progress could be the course guide progress, like today. What do you think?

**Comment by faloi** [comment]
Right now that's what happens when you enter student guide progress view:
the last exercise is selected.

I do like your idea of the different links.
