### ISSUE TITLE
Provide guide title in meta.yml file

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#228]

**Comment by faloi** [comment]
@flbulgarelli: same question here (see #330): how should we automate the export of titles to the `meta.yml` file?

**Comment by flbulgarelli** [comment]
A rake task will be ok. But in this case, it does not exits, you have to manually create it. 

The problem is that now we have several platforms, manually running the rake task is a bit tedious. We should investigate if we can run it within a migration. Check here: http://stackoverflow.com/questions/2632138/execute-a-rake-task-from-within-migration
