### ISSUE TITLE
translation missing: es.expectation_DoesTypeTest

### ISSUE THREAD

**Issue by PalumboN** [mumuki/mumuki-platform#237]
In this exercise: http://pdp-unsam.mumuki.io/exercises/2302-programacion-funcional-practica-listas-cuantas-muzzas

Resolved with this
```
cuantasMuzzas = ceiling.(/8).sum.(map snd).(filter soloMuzzas)
 
soloMuzzas pedido = fst pedido == "muzza"
```

Says:
```
Objetivos que no se cumplieron:
 translation missing: es.expectation_DoesTypeTest
```

In bibliotheca I don't find any error with the expectations: http://bibliotheca.mumuki.io/#!/guides/pdep-utn/mumuki-guia-funcional-practica-listas/exercises/322

PD: I'm not sure if this kind of issues go here. Sorry if it isn't!

**Comment by flbulgarelli** [comment]
> PD: I'm not sure if this kind of issues go here. Sorry if it isn't!

It is ok to report this issue here - this repository is the default place to send issues.

> In bibliotheca I don't find any error with the expectations: http://bibliotheca.mumuki.io/#!/guides/pdep-utn/mumuki-guia-funcional-practica-listas/exercises/322

And you won't find it :smile:! This is a `smell`, not an `expectation`, so it will be checked implicitly. 

The main problem is here: 

https://github.com/mumuki/mumukit-inspection/blob/master/lib/locales/es.yml

Could you add the missing translation @PalumboN?

Then there is another issue, that is a long standing one: mulang has no option to control `smell`s. They will be reported always. It would be nice to be able to disable it in some exercises - for example, in this one it is expected to perform a type test. We would be glad of receiving a PR to https://github.com/mumuki/mulang with this feature.

**Comment by PalumboN** [comment]
Ok! So I see [here](https://github.com/mumuki/mulang/blob/71aba57fcc476805fdabdf2a51cd3600b1b23c1e/src/Language/Mulang/Inspector/Smell.hs) that `DoesTypeTest` checks if exist a String comparison. That's ok or is more general? (I'm doubting because the smell's name)

**Comment by flbulgarelli** [comment]
> Ok! So I see here that DoesTypeTest checks if exist a String comparison. That's ok or is more general? 

Yes, the motivation behind this smell is to be able to detect code like

```
if x == "y" then ...
else if x == "z" then ...
```

So, perhaps there is another problem here: we should consider a type test only to string comparisons that are in an `if` of `case` expression :thinking:

**Comment by PalumboN** [comment]
Perfect, I understood!
So I create this PR for the translations: https://github.com/mumuki/mumukit-inspection/pull/1
And these Issues:
https://github.com/mumuki/mulang/issues/52
https://github.com/mumuki/mulang/issues/53

I'll playing with Mulang once I get to update cabal :)

**Comment by flbulgarelli** [comment]
Awesome, you rock :metal:
